### ISSUE TITLE
Warna Untuk Qalqalah Terlalu Gelap

### ISSUE THREAD

**Issue by dedychaidir** [kodepandai/colorful-quran#75]
![image](https://github.com/kodepandai/colorful-quran/assets/10151401/b9ec7bef-1d9b-401b-b803-e6cf4c945672)

Apakah warna untuk qalqalah bisa diganti dengan yang agak terang? Karena sangat mengganggu saat membaca ketika bertemu dengan qalqalah, huruf tidak kelihatan.

**Comment by axmad386** [comment]
Wah, terimakasih @dedychaidir atas masukannya. Betul sekali, warnanya kurang kontras saat di dark mode ya. Mungkin nanti bisa kami bedakan settingan warna tajwid saat di light dan dark mode, jadi agar tetap nyaman dibaca.

**Comment by axmad386** [comment]
@dedychaidir sudah diupdate untuk warna tajwid qalqalah di dark mode. Semoga lebih nyaman saat dibaca :)
![image](https://github.com/kodepandai/colorful-quran/assets/8775678/1b6b6b4f-172d-4eb9-a66c-0d36c557e731)
N.B: kalau belum berubah warnanya, bisa direfresh kalau dibuka menggunakan browser. Atau diclose dan open lagi kalau dibuka dari TWA (dari playstore)

**Comment by axmad386** [comment]
Ijin saya close issuenya, silakan reopen kalau masih ada problem

**Comment by dedychaidir** [comment]
Baik, terima kasih atas perhatiannya. Akan saya coba kembali dan bilamana ada kendala, akan saya laporkan lagi dengan membuat issue yang baru.
