### ISSUE TITLE
Warna Font dalam TextArea pada Modal Dialog Go to Ayat dalam tema gelap kurang jelas

### ISSUE THREAD

**Issue by dedychaidir** [kodepandai/colorful-quran#76]
![image](https://github.com/kodepandai/colorful-quran/assets/10151401/ec396ac8-2925-4aa2-98eb-fe74e715c40c)

Adakalanya ketika membaca suatu surat terjeda (tidak sampai tuntas satu surat). Sehingga saya menyimpan titik surat dan ayat terakhir yang saya baca dalam catatan saya sendiri, misal 9:28 (At Taubah, ayat ke 28). 
Lalu disaat ketika ingin lanjut membaca lagi, saya membuka surat tersebut dan mengklik Go To Ayat untuk mengetik ayatnya. Nah, dalam dark mode, ketikan font angka yang tampil kurang terang/jelas. 
Apakah bisa style font tersebut dijadikan semisal bold atau lebih darker agar lebih jelas?

**Comment by axmad386** [comment]
Sudah diperbaiki, dan disesuaikan ukuran inputnya
![image](https://github.com/kodepandai/colorful-quran/assets/8775678/21c69acc-a4de-4890-8b81-2a52d0efb233)
Semoga lebih nyaman digunakan :)

**Comment by dedychaidir** [comment]
Sedang saya coba dan sudah berubah. Terima kasih.
